<a href="https://colab.research.google.com/github/VennelaPulavarti/NNandDLclass3/blob/main/NN%26DL_ICP_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Github Link :

video explanation link :

submission confirmation number :

In [16]:
# QUE 1

class Employee:
    # DATA MEMBER TO COUNT THE NUMBER OF EMPLOYEES
    empCount = 0

    # CONSTRUCTOR TO INITIALIZE NAME, FAMILY, SALARY, DEPARTMENT
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.empCount += 1    # EMPLOYEE COUNT

    # FUNCTION FOR AVERAGE SALARY OF EMPLOYEE
    def avg_salary(self):
        total_salary = 0
        total_salary += float(self.salary)
        avg = total_salary / Employee.empCount
        print('Average salary of the Employee:', avg)

    # TO DISPLAY DETAILS OF EMPLOYEE
    def display(self):
        print('Employee Name:', self.name)
        print('Family Members:', self.family)
        print('Employee Annual Salary:', self.salary)
        print('Department:', self.department)
        print("==========")

# INHERITING - EMPLOYEE CLASS
class Fulltime_Employee(Employee):
    def __init__(self, name, family, salary, department, emp_type):
        Employee.__init__(self, name, family, salary, department)
        self.emp_type = emp_type

    #FUNCTION TO DISPLAY EMPLOYEE DETAILS
    def display(self):
        print("Employee Name :", self.name)
        print('Family Members:', self.family)
        print('Employee Annual Salary:', self.salary)
        print('Department:', self.department)
        print('Type of Employment :', self.emp_type)
        print("==========")


# INSTANCES FOR EMPLOYEE CLASS
emp1 = Employee('Vennela', '4', '650000', 'Software Engineer')
# INSTANCE FOR FULL TIME EMPLOYEE
emp2 = Fulltime_Employee('Varshitha', '5', '516000', 'Software Engineer', 'Fulltime')
emp3 = Fulltime_Employee('Aashritha', '5', '900000', 'Web Developer', 'Fulltime')

print("Count of the Employees :", emp1.empCount)
emp1.avg_salary()
emp1.display()
emp2.display()
emp3.display()

Count of the Employees : 3
Average salary of the Employee: 216666.66666666666
Employee Name: Vennela
Family Members: 4
Employee Annual Salary: 650000
Department: Software Engineer
Employee Name : Varshitha
Family Members: 5
Employee Annual Salary: 516000
Department: Software Engineer
Type of Employment : Fulltime
Employee Name : Aashritha
Family Members: 5
Employee Annual Salary: 900000
Department: Web Developer
Type of Employment : Fulltime


In [21]:
# QUE 2

import numpy as np

# creating array of size 20
random_vector = np.random.uniform(1, 20, 20)
print("Random Vector : \n", random_vector)

# reshape the array to 4 by 5
random_vector = random_vector.reshape(4,5)
print("after reshaping (4 by 5): \n", random_vector)

# replace the max in each row
random_vector[np.arange(len(random_vector)), random_vector.argmax(1)] = 0
print("Replacing the max in each row : \n", random_vector)

Random Vector : 
 [ 6.85413382  5.35001835  2.28551469  8.06611938  5.53056572 19.3025633
 17.02334194 16.95594993 16.83998001  8.82515504 12.35020309 10.07138126
  7.09661694  8.30452432 13.77731602  4.66110864  6.47533394 17.71567985
  8.96487699 14.96469421]
after reshaping (4 by 5): 
 [[ 6.85413382  5.35001835  2.28551469  8.06611938  5.53056572]
 [19.3025633  17.02334194 16.95594993 16.83998001  8.82515504]
 [12.35020309 10.07138126  7.09661694  8.30452432 13.77731602]
 [ 4.66110864  6.47533394 17.71567985  8.96487699 14.96469421]]
Replacing the max in each row : 
 [[ 6.85413382  5.35001835  2.28551469  0.          5.53056572]
 [ 0.         17.02334194 16.95594993 16.83998001  8.82515504]
 [12.35020309 10.07138126  7.09661694  8.30452432  0.        ]
 [ 4.66110864  6.47533394  0.          8.96487699 14.96469421]]
